# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            My Artisanal Life
tagline:          'Living an Artisanal Life '
description:      ''
url:              http://myartisanallife.com
baseurl:          '/'
paginate:         5

author:
  name:           'Andrew Froug'
  url:            https://twitter.com/andrewfroug

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/andrewfroug/andrewfroug.github.io
